language: node_js
node_js:
  - 'v14.16.0'
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
env:
  global:
    - MONGODB_URI=empty
    - MONGODB_DB=empty
    - SECRET_COOKIE_PASSWORD=empty
    - COOKIE_NAME=empty
    - CLOUDINARY_URL=empty
    - URL_LANDINGS=empty
before_install:
  - npm install -g npm
script:
  - npm run lint
  - npm run type-check
  - npm run build
  - npm run bundle-check
