export const ADD_BLOCK = 'DASHBOARD_PAGE/ADD_BLOCK';
export const EDIT_BLOCK = 'DASHBOARD_PAGE/EDIT_BLOCK';
export const REMOVE_BLOCK = 'DASHBOARD_PAGE/REMOVE_BLOCK';
export const SORT_BLOCK = 'DASHBOARD_PAGE/SORT_BLOCK';