export const ADD_BLOCK = 'DASHBOARD_PAGE/ADD_BLOCK';
export const EDIT_BLOCK = 'DASHBOARD_PAGE/EDIT_BLOCK';
export const REMOVE_BLOCK = 'DASHBOARD_PAGE/REMOVE_BLOCK';
export const SORT_BLOCK = 'DASHBOARD_PAGE/SORT_BLOCK';
export const UPDATE_LANDING = 'DASHBOARD_PAGE/UPDATE_LANDING';
export const SAVE_LANDING_SUCCESS = 'DASHBOARD_PAGE/SAVE_LANDING_SUCCESS';
export const LOADING = 'DASHBOARD_PAGE/LOADING';
export const HAS_ERROR = 'DASHBOARD_PAGE/HAS_ERROR';
