export const CHANGE_INPUT = 'PROFILE_PAGE/CHANGE_INPUT';
export const CHANGE_PASSWORD = 'PROFILE_PAGE/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'PROFILE_PAGE/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'PROFILE_PAGE/CHANGE_PASSWORD_ERROR';
