export const CHANGE_INPUT = 'REGISTER_PAGE/CHANGE_INPUT';
export const REGISTER = 'REGISTER_PAGE/REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_PAGE/REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_PAGE/REGISTER_ERROR';
