export const DELETE = 'DELETE';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';
export const DELETE_INTENTION = 'DELETE_INTENTION';
export const DELETE_INTENTION_CANCEL = 'DELETE_INTENTION_CANCEL';
export const DELETE_INTENTION_CONFIRM = 'DELETE_INTENTION_CONFIRM';
