export const DELETE = 'LANDINGS_PAGE/DELETE';
export const DELETE_SUCCESS = 'LANDINGS_PAGE/DELETE_SUCCESS';
export const DELETE_ERROR = 'LANDINGS_PAGE/DELETE_ERROR';
export const DELETE_INTENTION = 'LANDINGS_PAGE/DELETE_INTENTION';
export const DELETE_INTENTION_CANCEL = 'LANDINGS_PAGE/DELETE_INTENTION_CANCEL';
export const DELETE_INTENTION_CONFIRM = 'LANDINGS_PAGE/DELETE_INTENTION_CONFIRM';
